<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use PDO;
use stdClass;


class inm_comprador extends _modelo_parent{
    public function __construct(PDO $link)
    {
        $tabla = 'inm_comprador';
        $columnas = array($tabla=>false,'inm_producto_infonavit'=>$tabla,'inm_attr_tipo_credito'=>$tabla,
            'inm_tipo_credito'=>'inm_attr_tipo_credito','inm_destino_credito'=>$tabla,'inm_plazo_credito_sc'=>$tabla);

        $campos_obligatorios = array('inm_producto_infonavit_id','inm_attr_tipo_credito_id','inm_destino_credito_id',
            'es_segundo_credito','inm_plazo_credito_sc_id','descuento_pension_alimenticia_dh',
            'descuento_pension_alimenticia_fc','monto_credito_solicitado_dh','monto_ahorro_voluntario');

        $columnas_extra= array();
        $renombres= array();

        $atributos_criticos = array('inm_producto_infonavit_id','inm_attr_tipo_credito_id','inm_destino_credito_id',
            'es_segundo_credito','inm_plazo_credito_sc_id','descuento_pension_alimenticia_dh',
            'descuento_pension_alimenticia_fc','monto_credito_solicitado_dh','monto_ahorro_voluntario');

        parent::__construct(link: $link, tabla: $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, columnas_extra: $columnas_extra, renombres: $renombres,
            atributos_criticos: $atributos_criticos);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Comprador de Vivienda';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {

        if(!isset($this->registro['descripcion'])){
            $descripcion = $this->registro['nombre'];
            $descripcion .= ' '.$this->registro['apellido_paterno'];
            $descripcion .= ' '.$this->registro['apellido_materno'];
            $descripcion .= ' '.$this->registro['nss'];
            $descripcion .= ' '.$this->registro['curp'];
            $descripcion .= ' '.$this->registro['rfc'];
            $this->registro['descripcion'] = $descripcion;
        }
        if(!isset($this->registro['inm_plazo_credito_sc_id'])){
            $this->registro['inm_plazo_credito_sc_id'] = 7;
        }

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar',data:  $r_alta_bd);
        }

        $razon_social = $r_alta_bd->registro_puro['nombre'];
        $razon_social .= $r_alta_bd->registro_puro['apellido_paterno'];
        $razon_social .= $r_alta_bd->registro_puro['apellido_materno'];

        $com_cliente_ins['razon_social'] = trim($razon_social);
        $com_cliente_ins['rfc'] = $this->registro['rfc'];
        $com_cliente_ins['dp_calle_pertenece_id'] = $this->registro['dp_calle_pertenece_id'];

        return $r_alta_bd;

    }


}