<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use PDO;
use stdClass;


class inm_opinion_valor extends _modelo_parent{
    public function __construct(PDO $link)
    {
        $tabla = 'inm_opinion_valor';
        $columnas = array($tabla=>false,'inm_ubicacion'=>$tabla,'inm_valuador'=>$tabla);

        $campos_obligatorios = array('inm_ubicacion_id','inm_valuador_id','monto_resultado','fecha','costo');

        $columnas_extra= array();
        $renombres= array();

        $atributos_criticos = array('inm_ubicacion_id','inm_valuador_id','monto_resultado','fecha','costo');

        parent::__construct(link: $link, tabla: $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, columnas_extra: $columnas_extra, renombres: $renombres,
            atributos_criticos: $atributos_criticos);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Opiniones de valor';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        $inm_ubicacion = (new inm_ubicacion(link: $this->link))->registro(
            registro_id: $this->registro['inm_ubicacion_id'],retorno_obj: true);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener ubicacion',data:  $inm_ubicacion);
        }
        $inm_valuador = (new inm_valuador(link: $this->link))->registro(
            registro_id: $this->registro['inm_valuador_id'],retorno_obj: true);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener inm_valuador',data:  $inm_valuador);
        }

        if(!isset($this->registro['descripcion'])){
            $descripcion = $inm_ubicacion->dp_estado_descripcion.' ';
            $descripcion .= $inm_ubicacion->dp_municipio_descripcion.' ';
            $descripcion .= $inm_ubicacion->dp_cp_descripcion.' ';
            $descripcion .= $inm_ubicacion->dp_colonia_descripcion.' ';
            $descripcion .= $inm_ubicacion->dp_calle_descripcion.' ';
            $descripcion .= $inm_ubicacion->inm_ubicacion_numero_exterior.' ';
            $descripcion .= $this->registro['fecha'].' ';
            $descripcion .= $inm_valuador->inm_valuador_descripcion;
            $descripcion = trim($descripcion);

            $this->registro['descripcion'] = $descripcion;
        }
        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar opcion', data: $r_alta_bd);
        }
        return $r_alta_bd;
    }


}