<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use PDO;
use stdClass;


class inm_precio extends _modelo_parent{
    public function __construct(PDO $link)
    {
        $tabla = 'inm_precio';
        $columnas = array($tabla=>false,'inm_ubicacion'=>$tabla,'inm_tipo_ubicacion'=>'inm_ubicacion',
            'dp_calle_pertenece'=>'inm_ubicacion','dp_colonia_postal'=>'dp_calle_pertenece',
            'dp_cp'=>'dp_colonia_postal','dp_municipio'=>'dp_cp','dp_estado'=>'dp_municipio','dp_pais'=>'dp_estado',
            'dp_calle'=>'dp_calle_pertenece','dp_colonia'=>'dp_colonia_postal','inm_institucion_hipotecaria'=>$tabla);

        $campos_obligatorios = array('precio_venta','porcentaje_descuento_maximo','porcentaje_comisiones_maximo',
            'monto_descuento_maximo','monto_comisiones_maximo','fecha_inicial','fecha_final',
            'porcentaje_devolucion_maximo','monto_devolucion_maximo','inm_ubicacion_id',
            'inm_institucion_hipotecaria_id');

        $columnas_extra= array();
        $renombres= array();

        $atributos_criticos = array('precio_venta','porcentaje_descuento_maximo','porcentaje_comisiones_maximo',
            'monto_descuento_maximo','monto_comisiones_maximo','fecha_inicial','fecha_final',
            'porcentaje_devolucion_maximo','monto_devolucion_maximo','inm_ubicacion_id',
            'inm_institucion_hipotecaria_id');

        parent::__construct(link: $link, tabla: $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, columnas_extra: $columnas_extra, renombres: $renombres,
            atributos_criticos: $atributos_criticos);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Precios de Ubicacion';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        if(!isset($this->registro['descripcion'])){
            $descripcion = $this->registro['inm_ubicacion_id'];
            $descripcion .= " ".$this->registro['precio_venta'];
            $descripcion .= " ".$this->registro['fecha_inicial'];
            $descripcion .= " ".$this->registro['fecha_final'];
            $descripcion .= " ".$this->registro['inm_institucion_hipotecaria_id'];
            $this->registro['descripcion'] = $descripcion;
        }

        if(!isset($this->registro['porcentaje_descuento_maximo'])){
            $this->registro['porcentaje_descuento_maximo'] = 0;
        }
        if(!isset($this->registro['monto_descuento_maximo'])){
            $this->registro['monto_descuento_maximo'] = 0;
        }
        if(!isset($this->registro['porcentaje_comisiones_maximo'])){
            $this->registro['porcentaje_comisiones_maximo'] = 0;
        }
        if(!isset($this->registro['monto_comisiones_maximo'])){
            $this->registro['monto_comisiones_maximo'] = 0;
        }
        if(!isset($this->registro['porcentaje_devolucion_maximo'])){
            $this->registro['porcentaje_devolucion_maximo'] = 0;
        }
        if(!isset($this->registro['monto_devolucion_maximo'])){
            $this->registro['monto_devolucion_maximo'] = 0;
        }   

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar',data:  $r_alta_bd);
        }
        return $r_alta_bd;
    }


}