<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use PDO;
use stdClass;

class inm_prospecto extends _modelo_parent{
    public function __construct(PDO $link)
    {
        $tabla = 'inm_prospecto';
        $columnas = array($tabla=>false,'com_prospecto'=>$tabla);

        $campos_obligatorios = array('com_prospecto_id');

        $columnas_extra= array();
        $renombres = array();

        $atributos_criticos = array('com_prospecto_id');


        $tipo_campos= array();


        parent::__construct(link: $link, tabla: $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, columnas_extra: $columnas_extra, renombres: $renombres,
            tipo_campos: $tipo_campos, atributos_criticos: $atributos_criticos);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Prospecto de Vivienda';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {

        $keys = array('nombre','apellido_paterno');
        $valida = $this->validacion->valida_existencia_keys(keys: $keys,registro:  $this->registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al validar registro',data:  $valida);
        }

        $keys = array('apellido_materno','nss','curp','rfc');

        foreach ($keys as $key){
            if(!isset($this->registro[$key])){
                $this->registro[$key] = '';
            }
        }


        if(!isset($this->registro['descripcion'])){
            $descripcion = $this->registro['nombre'];
            $descripcion .= ' '.$this->registro['apellido_paterno'];
            $descripcion .= ' '.$this->registro['apellido_materno'];
            $descripcion .= ' '.$this->registro['nss'];
            $descripcion .= ' '.$this->registro['curp'];
            $descripcion .= ' '.$this->registro['rfc'];

            $this->registro['descripcion'] = $descripcion;
        }

        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar prospecto',data:  $r_alta_bd);
        }
        return $r_alta_bd;
    }


}