<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use PDO;


class inm_notaria extends _modelo_parent{
    public function __construct(PDO $link)
    {
        $tabla = 'inm_notaria';
        $columnas = array($tabla=>false,'dp_municipio'=>$tabla,'gt_proveedor'=>$tabla);

        $columnas_extra= array();
        $renombres= array();


        parent::__construct(link: $link, tabla: $tabla, columnas: $columnas, columnas_extra: $columnas_extra,
            renombres: $renombres);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Notaria';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|\stdClass
    {
        if (!isset($this->registro['descripcion'])) {
            $descripcion = $this->registro['gt_proveedor_id'];
            $descripcion .= $this->registro['dp_municipio_id'];
            $descripcion .= $this->registro['numero_notaria'];
            $descripcion .= mt_rand(1000, 9999);

            $this->registro['descripcion'] = $descripcion;
        }
    
        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar',data:  $r_alta_bd);
        }

        return $r_alta_bd;
    }

}