<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use PDO;
use stdClass;


class inm_precio extends _modelo_parent{
    public function __construct(PDO $link)
    {
        $tabla = 'inm_precio';
        $columnas = array($tabla=>false,'inm_ubicacion'=>$tabla,'inm_tipo_ubicacion'=>'inm_ubicacion',
            'dp_calle_pertenece'=>'inm_ubicacion','dp_colonia_postal'=>'dp_calle_pertenece',
            'dp_cp'=>'dp_colonia_postal','dp_municipio'=>'dp_cp','dp_estado'=>'dp_municipio','dp_pais'=>'dp_estado',
            'dp_calle'=>'dp_calle_pertenece','dp_colonia'=>'dp_colonia_postal','inm_institucion_hipotecaria'=>$tabla);

        $campos_obligatorios = array('precio_venta','porcentaje_descuento_maximo','porcentaje_comisiones_maximo',
            'monto_descuento_maximo','monto_comisiones_maximo','fecha_inicial','fecha_final',
            'porcentaje_devolucion_maximo','monto_devolucion_maximo','inm_ubicacion_id',
            'inm_institucion_hipotecaria_id');

        $columnas_extra= array();
        $renombres= array();

        $atributos_criticos = array('precio_venta','porcentaje_descuento_maximo','porcentaje_comisiones_maximo',
            'monto_descuento_maximo','monto_comisiones_maximo','fecha_inicial','fecha_final',
            'porcentaje_devolucion_maximo','monto_devolucion_maximo','inm_ubicacion_id',
            'inm_institucion_hipotecaria_id');

        parent::__construct(link: $link, tabla: $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, columnas_extra: $columnas_extra, renombres: $renombres,
            atributos_criticos: $atributos_criticos);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Precios de Ubicacion';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {

        if(!isset($this->registro['porcentaje_descuento_maximo'])){
            $this->registro['porcentaje_descuento_maximo'] = 0;
        }
        if(!isset($this->registro['monto_descuento_maximo'])){
            $this->registro['monto_descuento_maximo'] = 0;
        }
        if(!isset($this->registro['porcentaje_comisiones_maximo'])){
            $this->registro['porcentaje_comisiones_maximo'] = 0;
        }
        if(!isset($this->registro['monto_comisiones_maximo'])){
            $this->registro['monto_comisiones_maximo'] = 0;
        }
        if(!isset($this->registro['porcentaje_devolucion_maximo'])){
            $this->registro['porcentaje_devolucion_maximo'] = 0;
        }
        if(!isset($this->registro['monto_devolucion_maximo'])){
            $this->registro['monto_devolucion_maximo'] = 0;
        }

        $keys = array('inm_ubicacion_id','precio_venta','fecha_inicial','fecha_final','inm_institucion_hipotecaria_id');
        $valida = $this->validacion->valida_existencia_keys(keys: $keys,registro:  $this->registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al valida registro',data:  $valida);
        }


        $keys = array('inm_ubicacion_id','inm_institucion_hipotecaria_id');
        $valida = $this->validacion->valida_ids(keys: $keys,registro:  $this->registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al valida registro',data:  $valida);
        }

        $keys = array('porcentaje_descuento_maximo','monto_descuento_maximo','porcentaje_comisiones_maximo',
            'monto_comisiones_maximo','porcentaje_devolucion_maximo','monto_devolucion_maximo','precio_venta');
        $valida = $this->validacion->valida_double_mayores_igual_0(keys: $keys,registro:  $this->registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al valida registro',data:  $valida);
        }

        $keys = array('precio_venta');
        $valida = $this->validacion->valida_double_mayores_0(keys: $keys,registro:  $this->registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al valida registro',data:  $valida);
        }

        $valida = $this->validacion->valida_rango_fecha($this->registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al valida registro',data:  $valida);
        }


        if(!isset($this->registro['descripcion'])){
            $descripcion = $this->registro['inm_ubicacion_id'];
            $descripcion .= " ".$this->registro['precio_venta'];
            $descripcion .= " ".$this->registro['fecha_inicial'];
            $descripcion .= " ".$this->registro['fecha_final'];
            $descripcion .= " ".$this->registro['inm_institucion_hipotecaria_id'];
            $this->registro['descripcion'] = $descripcion;
        }



        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar',data:  $r_alta_bd);
        }
        return $r_alta_bd;
    }

    /**
     * @param string $fecha
     * @param int $inm_ubicacion_id
     * @param int $inm_institucion_hipotecaria_id
     * @param bool $retorno_obj
     * @return array|stdClass
     */
    final public function precio(string $fecha, int $inm_ubicacion_id, int $inm_institucion_hipotecaria_id,
                                 bool $retorno_obj = true): array|stdClass
    {
        $fecha = trim($fecha);;
        if($fecha === ''){
            return $this->error->error(mensaje: 'Error fecha esta vacio',data:  $fecha);
        }

        if($inm_ubicacion_id <= 0){
            return $this->error->error(mensaje: 'Error inm_ubicacion_id debe ser mayor a 0',data:  $inm_ubicacion_id);
        }

        if($inm_institucion_hipotecaria_id <= 0){
            return $this->error->error(mensaje: 'Error inm_institucion_hipotecaria_id debe ser mayor a 0',
                data:  $inm_institucion_hipotecaria_id);
        }

        $filtro['inm_ubicacion.id'] = $inm_ubicacion_id;
        $filtro['inm_institucion_hipotecaria.id'] = $inm_institucion_hipotecaria_id;

        $filtro_fecha[0]['campo_1'] = 'inm_precio.fecha_inicial';
        $filtro_fecha[0]['campo_2'] = 'inm_precio.fecha_final';
        $filtro_fecha[0]['fecha'] = $fecha;

        $r_inm_precio = $this->filtro_and(filtro: $filtro,filtro_fecha: $filtro_fecha);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener precio',data:  $r_inm_precio);
        }

        if($r_inm_precio->n_registros === 0){
            return $this->error->error(mensaje: 'Error no existe precio configurado',data:  $r_inm_precio);
        }
        if($r_inm_precio->n_registros > 1){
            return $this->error->error(mensaje: 'Error existe mas de un precio configurado',data:  $r_inm_precio);
        }

        $inm_precio = $r_inm_precio->registros[0];
        if($retorno_obj){
            $inm_precio = (object)$inm_precio;
        }

        return $inm_precio;


    }


}