<?php

namespace gamboamartin\inmuebles\models;

use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use PDO;
use stdClass;


class inm_rel_prospecto_cliente extends _modelo_parent{
    public function __construct(PDO $link)
    {
        $tabla = 'inm_rel_prospecto_cliente';
        $columnas = array($tabla=>false,'inm_prospecto'=>$tabla, 'inm_comprador'=>$tabla);

        $campos_obligatorios = array('inm_prospecto_id','inm_comprador_id');

        $columnas_extra= array();
        $renombres= array();

        $atributos_criticos = array('inm_prospecto_id','inm_comprador_id');


        parent::__construct(link: $link, tabla: $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, columnas_extra: $columnas_extra, renombres: $renombres,
            atributos_criticos: $atributos_criticos);

        $this->NAMESPACE = __NAMESPACE__;
        $this->etiqueta = 'Relacion cliente prospecto';
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {

        $valida = $this->valida_alta_relacion(registro: $this->registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al validar $registro',data: $valida);
        }

        if(!isset($this->registro['descripcion'])){
            $descripcion = $this->descripcion(registro: $this->registro );
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al obtener descripcion',data:  $descripcion);
            }

            $this->registro['descripcion'] = $descripcion;
        }

        /*
        //$filtro['inm_prospecto.id'] = $this->registro['inm_prospecto_id'];
        $filtro['inm_comprador.id'] = $this->registro['inm_comprador_id'];

        $existe = $this->existe(filtro: $filtro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al validar si existe relacion',data:  $existe);
        }
        if($existe){

            $r_inm_rel_prospecto_cliente = $this->filtro_and(filtro: $filtro);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al obtener inm_rel_prospecto_cliente',
                    data:  $r_inm_rel_prospecto_cliente);
            }
            $registro = $r_inm_rel_prospecto_cliente->registros[0];

            $registro_puro = $this->registro(registro_id: $registro['inm_rel_prospecto_cliente_id'],
                columnas_en_bruto: true, retorno_obj: true);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al obtener registro puro', data: $registro_puro);
            }

            $r_alta_bd = $this->data_result_transaccion(mensaje: 'Registro insertado previamente', registro: $registro,
                registro_ejecutado: $this->registro, registro_id: $registro_puro->id, registro_puro: $registro_puro,
                sql: 'SELECT');
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al maquetar respuesta registro', data: $registro);
            }
        }
        else {*/
            $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al insertar', data: $r_alta_bd);
            }
        /*}*/

        return $r_alta_bd;

    }

    private function descripcion(array $registro): string|array
    {

        $valida = $this->valida_alta_relacion(registro: $registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al validar $registro',data: $valida);
        }

        $descripcion = $registro['inm_comprador_id'];
        $descripcion .= ' '.$registro['inm_prospecto_id'];
        return $descripcion;
    }

    private function valida_alta_relacion(array $registro){

        $keys = array('inm_comprador_id','inm_prospecto_id');
        $valida = $this->validacion->valida_ids(keys: $keys,registro:  $registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al validar $registro',data: $valida);
        }
        return true;
    }


}